modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/tasgon/observable/issues"
license = "MPL"

[[mods]]
modId = "observable"
version = "${version}"
displayName = "Observable"
authors = "tasgon"
logoFile = "icon.png"
description = '''
See what's lagging your world.
'''

[[dependencies.observable]]
modId = "architectury"
type = "required"
versionRange = "[20.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.observable]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.observable]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "observable.common.json"

