modLoader="javafml"
loaderVersion="[1,)"
license="LGPLv3"

[[mods]]
modId="observable"
version="5.4.3"
displayName="Observable"
authors="tasgon, nef, Polypheides"
logoFile="icon.png"
description="Real-time profiling of entities and block entities."

[[dependencies.observable]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="observable.common.mixin.json"

[[mixins]]
config="observable.common.accessors.json"
side="client"
